name: "01-EKS"

on:
  push:
    branches:
      - master

jobs:
  Plan:
    uses: NiksaJadric/EADCA2-infrastructure/.github/workflows/aws_tf_plan.yml@master
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Apply:
    needs: Plan
    uses: NiksaJadric/EADCA2-infrastructure/.github/workflows/aws_tf_appy.yml@master
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}